# SonarQube analysis GitHub Action workflow
name: SonarQube analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # better blame & PR analysis

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     # for PR decoration
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}      # your SQ token (secret)
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # e.g., https://sonarqube.myorg.com
        with:
          args: >
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            -Dsonar.qualitygate.wait=true          # optional: fail job if QG fails
